Repository school-accreditation-system/frontend, pull requests merged in 2025-03, with the labels that each got.

#4 Added landing page and login page
  package.json
  pnpm-lock.yaml
  public/nesa-logo.png
  public/public/file.svg
  public/public/globe.svg
  public/public/nesa-logo.png
  public/public/next.svg
  public/public/vercel.svg
  public/public/window.svg
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/components/accreditation/AboutSection.tsx
  src/components/accreditation/HeroSection.tsx
  src/components/accreditation/ProcessStepsSection.tsx
  src/components/accreditation/RequestTypesSection.tsx
  src/components/accreditation/ServicesSection.tsx
  src/components/auth/AuthForm.tsx
  src/components/auth/AuthSteps.tsx
  src/components/layout/Footer.tsx
  src/components/ui/FeatureCard.tsx
  src/components/ui/IconWrapper.tsx
  src/components/ui/StepCard.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/input.tsx
  src/components/ui/separator.tsx
  src/lib/utils.ts
  tailwind.config.js
Labels: enhancement

#8 Feat: Add implementation to apply for tvet
  src/app/general-combination/_components/CombinationSelector.tsx
  src/app/tvet-trades/_components/ConfirmationModal.tsx
  src/app/tvet-trades/_components/FormActions.tsx
  src/app/tvet-trades/_components/FormField.tsx
  src/app/tvet-trades/_components/FormSteps.tsx
  src/app/tvet-trades/_components/SchoolIdentification.tsx
  src/app/tvet-trades/_components/SelectField.tsx
  src/app/tvet-trades/_components/SelfAssessment.tsx
  src/app/tvet-trades/_components/SuccessModal.tsx
  src/app/tvet-trades/_components/SummaryPage.tsx
  src/app/tvet-trades/_components/TvetTradesSelector.tsx
  src/app/tvet-trades/_components/basicValidators.ts
  src/app/tvet-trades/_components/generateTradeDetails.ts
  src/app/tvet-trades/_components/validation.ts
  src/app/tvet-trades/page.tsx
  utils/RequestTypes.ts
  utils/schoolsData.ts
  utils/tvetData.ts
Labels: Ready

#9 Feat: Add submit-claim form
  src/app/submit-claim/page.tsx
  utils/RequestTypes.ts
Labels: Ready

#10 Feature: Add professional-combination form
  src/app/layout.tsx
  src/app/professional-combination/_components/CombinationSelector.tsx
  src/app/professional-combination/_components/ConfirmationModal.tsx
  src/app/professional-combination/_components/FormActions.tsx
  src/app/professional-combination/_components/FormField.tsx
  src/app/professional-combination/_components/FormSteps.tsx
  src/app/professional-combination/_components/ProfessionalProgramSelector.tsx
  src/app/professional-combination/_components/SchoolIdentification.tsx
  src/app/professional-combination/_components/SelectField.tsx
  src/app/professional-combination/_components/SelfAssessment.tsx
  src/app/professional-combination/_components/SuccessModal.tsx
  src/app/professional-combination/_components/SummaryPage.tsx
  src/app/professional-combination/_components/basicValidators.ts
  src/app/professional-combination/_components/validation.ts
  src/app/professional-combination/page.tsx
  utils/RequestTypes.ts
Labels: Ready

#11 Add ordinary level form
  src/app/ordinary-level/_components/SchoolApplicationPage.tsx
  src/app/ordinary-level/_components/SuccessModal.tsx
  src/app/ordinary-level/page.tsx
  utils/RequestTypes.ts
  utils/schoolsData.ts
Labels: Ready

#13 Feature: add pre primary level form
  src/app/pre-primary-level/_components/SchoolApplicationPage.tsx
  src/app/pre-primary-level/_components/SuccessModal.tsx
  src/app/pre-primary-level/page.tsx
  utils/RequestTypes.ts
Labels: Ready

#20 Add image from import
  next.config.ts
  src/components/accreditation/HeroSection.tsx
Labels: Ready

#21 Refact: components,navbar
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/general-combination/_components/CategorySelector.tsx
  src/app/general-combination/_components/CombinationList.tsx
  src/app/general-combination/_components/CombinationSelector.tsx
  src/app/general-combination/_components/FormSteps.tsx
  src/app/general-combination/_components/NavigationButtons.tsx
  src/app/general-combination/_components/SelectedCombinations.tsx
  src/app/general-combination/_components/generateCombinationDetails.ts
  src/app/general-combination/page.tsx
  src/app/layout.tsx
  src/app/school-identification/page.tsx
  src/app/slicers/DialogSlice.ts
  src/app/slicers/RequestTypeSlice.ts
  src/app/slicers/index.ts
  src/app/store/StoreProvider.tsx
  src/app/store/index.ts
  src/app/store/store.ts
  src/components/accreditation/HeroSection.tsx
  src/components/accreditation/RequestTypesSection.tsx
  src/components/navigation/NavBar.tsx
  src/components/school-finder/SchoolFinderDialog.tsx
  src/components/school-identification/context/FormContext.tsx
  src/lib/index.ts
  src/lib/useEmail.ts
Labels: Frontend, enhancement
