Repository school-accreditation-system/frontend, pull requests merged in 2025-04, with the labels that each got.

#22 Added sign up and accredited school page
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/accredited-schools/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/accreditation/HeroSection.tsx
  src/components/accredited-schools/Pagination.tsx
  src/components/accredited-schools/SchoolCard.tsx
  src/components/accredited-schools/SearchFilters.tsx
  src/components/accredited-schools/index.ts
  src/components/auth/AuthForm.tsx
  src/components/auth/StaffLoginForm.tsx
  src/components/auth/StaffSignupForm.tsx
  src/components/auth/types/schema.ts
Labels: Frontend

#23 refact homepage
  src/app/application-status/layout.tsx
  src/app/application-status/page.tsx
  src/app/verify-certificate/layout.tsx
  src/app/verify-certificate/page.tsx
  src/components/accreditation/HeroSection.tsx
  src/components/accreditation/RequestTypesSection.tsx
  src/components/accreditation/ServicesSection.tsx
  src/components/navigation/NavBar.tsx
  src/constants/RequestTypes.ts
Labels: Frontend, enhancement

#17 Initial commit for self aseessment
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/self-assessment/page.tsx
  src/components/selfAssessment/SchoolAssessmentSteps.tsx
  src/components/selfAssessment/constanst.ts
  src/components/selfAssessment/context/FormContext.tsx
  src/components/selfAssessment/context/index.ts
  src/components/selfAssessment/steps/LandOwnershipForm.tsx
  src/components/selfAssessment/steps/ProvisionalResults.tsx
  src/components/selfAssessment/steps/SchoolInfrastructureForm.tsx
  src/components/selfAssessment/steps/TeachingResourcesForm.tsx
  src/components/selfAssessment/steps/TypeofRequestForm.tsx
  src/components/selfAssessment/types/schema.ts
  src/components/selfAssessment/types/step.ts
  src/components/ui/checkbox.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/select.tsx
  src/components/ui/tabs.tsx
Labels: bug, Frontend

#25 update track application and verify-certificate
  package-lock.json
  public/accredited-logo.jpg
  public/nesalogo-removebg.png
  src/app/application-status/page.tsx
  src/app/general-combination/page.tsx
  src/app/verify-certificate/_components/printCertificate.tsx
  src/app/verify-certificate/page.tsx
  src/components/selfAssessment/context/FormContext.tsx
Labels: Frontend, enhancement

#38 Refactor: improve management dashboards
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/inspection-plan/inspections/page.tsx
  src/app/inspection-plan/layout.tsx
  src/app/inspection-plan/teams/page.tsx
  src/app/inspector-dashboard/applications/page.tsx
  src/app/inspector-dashboard/layout.tsx
  src/app/management-dashboard/applications/page.tsx
  src/components/auth/StaffLoginForm.tsx
  src/components/inspection-plan/_components/Header.tsx
  src/components/inspection-plan/_components/Sidebar.tsx
  src/components/inspection-plan/_components/Table.tsx
  src/components/inspector-dashboard/_components/Sidebar.tsx
  src/components/management-dashboard/_components/Header.tsx
  src/components/management-dashboard/_components/Sidebar.tsx
  src/components/ui/calendar.tsx
  src/components/ui/popover.tsx
Labels: enhancement
